// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: article.sql

package adminmodel

import (
	"context"
	"time"
)

const countArticles = `-- name: CountArticles :one
SELECT
    count(*)
FROM
    articles
`

func (q *Queries) CountArticles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArticles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArticlesBySlug = `-- name: CountArticlesBySlug :one
SELECT
    count(*)
FROM
    articles
WHERE
    slug = ?
`

func (q *Queries) CountArticlesBySlug(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArticlesBySlug, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :execlastid
INSERT INTO
    articles (
        title,
        date,
        author,
        content,
        slug,
        draft,
        layout_id
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?)
`

type CreateArticleParams struct {
	Title    string
	Date     time.Time
	Author   string
	Content  string
	Slug     string
	Draft    int64
	LayoutID int64
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createArticle,
		arg.Title,
		arg.Date,
		arg.Author,
		arg.Content,
		arg.Slug,
		arg.Draft,
		arg.LayoutID,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles
WHERE
    slug = ?
`

func (q *Queries) DeleteArticle(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, deleteArticle, slug)
	return err
}

const getArticlesList = `-- name: GetArticlesList :many
SELECT
    title,
    date,
    author,
    slug,
    draft
FROM
    articles
ORDER BY
    date DESC
LIMIT
    ?
OFFSET
    ?
`

type GetArticlesListParams struct {
	Limit  int64
	Offset int64
}

type GetArticlesListRow struct {
	Title  string
	Date   time.Time
	Author string
	Slug   string
	Draft  int64
}

func (q *Queries) GetArticlesList(ctx context.Context, arg GetArticlesListParams) ([]GetArticlesListRow, error) {
	rows, err := q.db.QueryContext(ctx, getArticlesList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArticlesListRow
	for rows.Next() {
		var i GetArticlesListRow
		if err := rows.Scan(
			&i.Title,
			&i.Date,
			&i.Author,
			&i.Slug,
			&i.Draft,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectArticleBySlug = `-- name: SelectArticleBySlug :many
SELECT
    id, title, date, author, content, slug, draft, layout_id
FROM
    articles
WHERE
    slug = ?
LIMIT
    1
`

func (q *Queries) SelectArticleBySlug(ctx context.Context, slug string) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, selectArticleBySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Date,
			&i.Author,
			&i.Content,
			&i.Slug,
			&i.Draft,
			&i.LayoutID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :exec
UPDATE articles
SET
    title = ?,
    date = ?,
    author = ?,
    content = ?,
    slug = ?,
    draft = ?,
    layout_id = ?
WHERE
    slug = ?
`

type UpdateArticleParams struct {
	Title    string
	Date     time.Time
	Author   string
	Content  string
	Slug     string
	Draft    int64
	LayoutID int64
	Slug_2   string
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) error {
	_, err := q.db.ExecContext(ctx, updateArticle,
		arg.Title,
		arg.Date,
		arg.Author,
		arg.Content,
		arg.Slug,
		arg.Draft,
		arg.LayoutID,
		arg.Slug_2,
	)
	return err
}
