// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: block_data.sql

package adminmodel

import (
	"context"
)

const countBlockDataByID = `-- name: CountBlockDataByID :one
SELECT
    count(*)
FROM
    block_data
WHERE
    id = ?
`

func (q *Queries) CountBlockDataByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBlockDataByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBlockData = `-- name: CreateBlockData :execlastid
INSERT INTO
    block_data (position, data, block_id, article_id)
VALUES
    (?, ?, ?, ?)
`

type CreateBlockDataParams struct {
	Position  int64
	Data      string
	BlockID   int64
	ArticleID int64
}

func (q *Queries) CreateBlockData(ctx context.Context, arg CreateBlockDataParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createBlockData,
		arg.Position,
		arg.Data,
		arg.BlockID,
		arg.ArticleID,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteBlockData = `-- name: DeleteBlockData :exec
DELETE FROM block_data
WHERE
    id = ?
`

func (q *Queries) DeleteBlockData(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBlockData, id)
	return err
}

const selectBlockDataByArticle = `-- name: SelectBlockDataByArticle :many
SELECT
    id, position, data, article_id, block_id
FROM
    block_data
WHERE
    article_id = ?
ORDER BY
    position DESC
`

func (q *Queries) SelectBlockDataByArticle(ctx context.Context, articleID int64) ([]BlockDatum, error) {
	rows, err := q.db.QueryContext(ctx, selectBlockDataByArticle, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlockDatum
	for rows.Next() {
		var i BlockDatum
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Data,
			&i.ArticleID,
			&i.BlockID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlockData = `-- name: UpdateBlockData :exec
UPDATE block_data
SET
    position = ?,
    data = ?
WHERE
    id = ?
`

type UpdateBlockDataParams struct {
	Position int64
	Data     string
	ID       int64
}

func (q *Queries) UpdateBlockData(ctx context.Context, arg UpdateBlockDataParams) error {
	_, err := q.db.ExecContext(ctx, updateBlockData, arg.Position, arg.Data, arg.ID)
	return err
}
