// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: layout.sql

package adminmodel

import (
	"context"
)

const countLayout = `-- name: CountLayout :one
SELECT
    count(*)
FROM
    layouts
`

func (q *Queries) CountLayout(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLayout)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLayoutByName = `-- name: CountLayoutByName :one
SELECT
    count(*)
FROM
    layouts
WHERE
    name = ?
`

func (q *Queries) CountLayoutByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLayoutByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLayout = `-- name: CreateLayout :execlastid
INSERT INTO
    layouts (name, content)
VALUES
    (?, ?)
`

type CreateLayoutParams struct {
	Name    string
	Content string
}

func (q *Queries) CreateLayout(ctx context.Context, arg CreateLayoutParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createLayout, arg.Name, arg.Content)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteLayout = `-- name: DeleteLayout :exec
DELETE FROM layouts
WHERE
    name = ?
`

func (q *Queries) DeleteLayout(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteLayout, name)
	return err
}

const geLayoutList = `-- name: GeLayoutList :many
SELECT
    name
FROM
    layouts
ORDER BY
    name DESC
LIMIT
    ?
OFFSET
    ?
`

type GeLayoutListParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GeLayoutList(ctx context.Context, arg GeLayoutListParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, geLayoutList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectLayout = `-- name: SelectLayout :many
SELECT
    id, name, content
FROM
    layouts
WHERE
    name = ?
LIMIT
    1
`

func (q *Queries) SelectLayout(ctx context.Context, name string) ([]Layout, error) {
	rows, err := q.db.QueryContext(ctx, selectLayout, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Layout
	for rows.Next() {
		var i Layout
		if err := rows.Scan(&i.ID, &i.Name, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLayout = `-- name: UpdateLayout :exec
UPDATE layouts
SET
    name = ?,
    content = ?
WHERE
    name = ?
`

type UpdateLayoutParams struct {
	Name    string
	Content string
	Name_2  string
}

func (q *Queries) UpdateLayout(ctx context.Context, arg UpdateLayoutParams) error {
	_, err := q.db.ExecContext(ctx, updateLayout, arg.Name, arg.Content, arg.Name_2)
	return err
}
