// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package adminmodel

import (
	"time"
)

type Article struct {
	ID      int64
	Title   string
	Date    time.Time
	Author  string
	Content string
	Slug    string
	Draft   int64
}

type File struct {
	ID      int64
	Name    string
	Content []byte
}

type Layout struct {
	ID      int64
	Name    string
	Content string
}

type Page struct {
	ID      int64
	Name    string
	Content string
}
