// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package adminmodel

import (
	"database/sql"
	"time"
)

type Article struct {
	ID      int64
	Title   string
	Date    time.Time
	Author  string
	Content string
	Slug    string
	Draft   sql.NullInt64
}

type File struct {
	ID      int64
	Name    string
	Content []byte
	Uuid    string
}

type Layout struct {
	ID      int64
	Name    string
	Content string
}
