// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: page.sql

package adminmodel

import (
	"context"
)

const countPage = `-- name: CountPage :one
SELECT
    count(*)
FROM
    pages
`

func (q *Queries) CountPage(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPage)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPageByName = `-- name: CountPageByName :one
SELECT
    count(*)
FROM
    pages
WHERE
    name = ?
`

func (q *Queries) CountPageByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPageByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPage = `-- name: CreatePage :execlastid
INSERT INTO
    pages (name, content)
VALUES
    (?, ?)
`

type CreatePageParams struct {
	Name    string
	Content string
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createPage, arg.Name, arg.Content)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM pages
WHERE
    name = ?
`

func (q *Queries) DeletePage(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deletePage, name)
	return err
}

const gePageList = `-- name: GePageList :many
SELECT
    name
FROM
    pages
ORDER BY
    name DESC
LIMIT
    ?
OFFSET
    ?
`

type GePageListParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GePageList(ctx context.Context, arg GePageListParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, gePageList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPage = `-- name: SelectPage :many
SELECT
    id, name, content
FROM
    pages
WHERE
    name = ?
LIMIT
    1
`

func (q *Queries) SelectPage(ctx context.Context, name string) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, selectPage, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(&i.ID, &i.Name, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePage = `-- name: UpdatePage :exec
UPDATE pages
SET
    name = ?,
    content = ?
WHERE
    name = ?
`

type UpdatePageParams struct {
	Name    string
	Content string
	Name_2  string
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) error {
	_, err := q.db.ExecContext(ctx, updatePage, arg.Name, arg.Content, arg.Name_2)
	return err
}
