// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: article.sql

package adminmodel

import (
	"context"
	"time"
)

const countArticleBySlug = `-- name: CountArticleBySlug :one
SELECT
    count(*)
FROM
    article
WHERE
    slug = ?
`

func (q *Queries) CountArticleBySlug(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArticleBySlug, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArticleLikeTitle = `-- name: CountArticleLikeTitle :one
SELECT
    count(*)
FROM
    article
WHERE
    title LIKE ?
`

func (q *Queries) CountArticleLikeTitle(ctx context.Context, title string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArticleLikeTitle, title)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :execlastid
INSERT INTO
    article (
        title,
        date,
        author,
        content,
        slug,
        draft,
        layout_id
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?)
`

type CreateArticleParams struct {
	Title    string
	Date     time.Time
	Author   string
	Content  string
	Slug     string
	Draft    int64
	LayoutID int64
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createArticle,
		arg.Title,
		arg.Date,
		arg.Author,
		arg.Content,
		arg.Slug,
		arg.Draft,
		arg.LayoutID,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM article
WHERE
    slug = ?
`

func (q *Queries) DeleteArticle(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, deleteArticle, slug)
	return err
}

const getArticleList = `-- name: GetArticleList :many
SELECT
    title,
    date,
    author,
    substr(content, 0, 50) AS ` + "`" + `content` + "`" + `,
    slug,
    draft
FROM
    article
WHERE
    title LIKE ?
ORDER BY
    date DESC
LIMIT
    ?
OFFSET
    ?
`

type GetArticleListParams struct {
	Title  string
	Limit  int64
	Offset int64
}

type GetArticleListRow struct {
	Title   string
	Date    time.Time
	Author  string
	Content string
	Slug    string
	Draft   int64
}

func (q *Queries) GetArticleList(ctx context.Context, arg GetArticleListParams) ([]GetArticleListRow, error) {
	rows, err := q.db.QueryContext(ctx, getArticleList, arg.Title, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArticleListRow
	for rows.Next() {
		var i GetArticleListRow
		if err := rows.Scan(
			&i.Title,
			&i.Date,
			&i.Author,
			&i.Content,
			&i.Slug,
			&i.Draft,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectArticleBySlug = `-- name: SelectArticleBySlug :many
SELECT
    id, title, date, author, content, slug, draft, layout_id
FROM
    article
WHERE
    slug = ?
LIMIT
    1
`

func (q *Queries) SelectArticleBySlug(ctx context.Context, slug string) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, selectArticleBySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Date,
			&i.Author,
			&i.Content,
			&i.Slug,
			&i.Draft,
			&i.LayoutID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :exec
UPDATE article
SET
    title = ?,
    date = ?,
    author = ?,
    content = ?,
    slug = ?,
    draft = ?,
    layout_id = ?
WHERE
    slug = ?
`

type UpdateArticleParams struct {
	Title    string
	Date     time.Time
	Author   string
	Content  string
	Slug     string
	Draft    int64
	LayoutID int64
	Slug_2   string
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) error {
	_, err := q.db.ExecContext(ctx, updateArticle,
		arg.Title,
		arg.Date,
		arg.Author,
		arg.Content,
		arg.Slug,
		arg.Draft,
		arg.LayoutID,
		arg.Slug_2,
	)
	return err
}
