// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: block.sql

package adminmodel

import (
	"context"
)

const countBlock = `-- name: CountBlock :one
SELECT
    count(*)
FROM
    block
`

func (q *Queries) CountBlock(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBlock)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBlockByID = `-- name: CountBlockByID :one
SELECT
    count(*)
FROM
    block
WHERE
    id = ?
`

func (q *Queries) CountBlockByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBlockByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBlockByName = `-- name: CountBlockByName :one
SELECT
    count(*)
FROM
    block
WHERE
    name = ?
`

func (q *Queries) CountBlockByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBlockByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBlock = `-- name: CreateBlock :execlastid
INSERT INTO
    block (name, content, definition)
VALUES
    (?, ?, ?)
`

type CreateBlockParams struct {
	Name       string
	Content    string
	Definition string
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createBlock, arg.Name, arg.Content, arg.Definition)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM block
WHERE
    name = ?
`

func (q *Queries) DeleteBlock(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteBlock, name)
	return err
}

const getBlockList = `-- name: GetBlockList :many
SELECT
    name
FROM
    block
ORDER BY
    name DESC
LIMIT
    ?
OFFSET
    ?
`

type GetBlockListParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GetBlockList(ctx context.Context, arg GetBlockListParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getBlockList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAllBlock = `-- name: SelectAllBlock :many
SELECT
    id, name, content, definition
FROM
    block
`

func (q *Queries) SelectAllBlock(ctx context.Context) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, selectAllBlock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.Definition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectBlock = `-- name: SelectBlock :many
SELECT
    id, name, content, definition
FROM
    block
WHERE
    name = ?
LIMIT
    1
`

func (q *Queries) SelectBlock(ctx context.Context, name string) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, selectBlock, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.Definition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectBlockByID = `-- name: SelectBlockByID :many
SELECT
    id, name, content, definition
FROM
    block
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) SelectBlockByID(ctx context.Context, id int64) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, selectBlockByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.Definition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlock = `-- name: UpdateBlock :exec
UPDATE block
SET
    name = ?,
    content = ?,
    definition = ?
WHERE
    name = ?
`

type UpdateBlockParams struct {
	Name       string
	Content    string
	Definition string
	Name_2     string
}

func (q *Queries) UpdateBlock(ctx context.Context, arg UpdateBlockParams) error {
	_, err := q.db.ExecContext(ctx, updateBlock,
		arg.Name,
		arg.Content,
		arg.Definition,
		arg.Name_2,
	)
	return err
}
