// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: file.sql

package adminmodel

import (
	"context"
)

const countFile = `-- name: CountFile :one
SELECT
    count(*)
FROM
    file
`

func (q *Queries) CountFile(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFile)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFileByName = `-- name: CountFileByName :one
SELECT
    count(*)
FROM
    file
WHERE
    name = ?
`

func (q *Queries) CountFileByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFileByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM file
WHERE
    name = ?
`

func (q *Queries) DeleteFile(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteFile, name)
	return err
}

const downloadFile = `-- name: DownloadFile :many
SELECT
    content
FROM
    file
WHERE
    name = ?
LIMIT
    1
`

func (q *Queries) DownloadFile(ctx context.Context, name string) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, downloadFile, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var content []byte
		if err := rows.Scan(&content); err != nil {
			return nil, err
		}
		items = append(items, content)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileList = `-- name: GetFileList :many
SELECT
    name
FROM
    file
ORDER BY
    id DESC
LIMIT
    ?
OFFSET
    ?
`

type GetFileListParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GetFileList(ctx context.Context, arg GetFileListParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getFileList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectFilesInFolderFile = `-- name: SelectFilesInFolderFile :many
SELECT
    substr(name, length(?1) + 1) AS filename
FROM file
WHERE name LIKE ?1 || '%'
AND instr(substr(name, length(?1) + 1), '/') = 0
`

func (q *Queries) SelectFilesInFolderFile(ctx context.Context, path interface{}) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, selectFilesInFolderFile, path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var filename string
		if err := rows.Scan(&filename); err != nil {
			return nil, err
		}
		items = append(items, filename)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectFoldersInFolderFile = `-- name: SelectFoldersInFolderFile :many
SELECT DISTINCT
  substr(
    substr(name, length(?1) + 1),
    1,
    instr(substr(name, length(?1) + 1), '/') - 1
  ) AS folder
FROM file
WHERE name LIKE ?1 || '%'
  AND instr(substr(name, length(?1) + 1), '/') > 0
`

func (q *Queries) SelectFoldersInFolderFile(ctx context.Context, path interface{}) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, selectFoldersInFolderFile, path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var folder string
		if err := rows.Scan(&folder); err != nil {
			return nil, err
		}
		items = append(items, folder)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uploadFile = `-- name: UploadFile :execlastid
INSERT INTO
    file (name, content)
VALUES
    (?, ?)
`

type UploadFileParams struct {
	Name    string
	Content []byte
}

func (q *Queries) UploadFile(ctx context.Context, arg UploadFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, uploadFile, arg.Name, arg.Content)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}
