// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: global.sql

package adminmodel

import (
	"context"
)

const getGlobalData = `-- name: GetGlobalData :one
SELECT
    content
FROM
    global
WHERE
    name = 'data'
LIMIT
    1
`

func (q *Queries) GetGlobalData(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getGlobalData)
	var content string
	err := row.Scan(&content)
	return content, err
}

const getGlobalDefinition = `-- name: GetGlobalDefinition :one
SELECT
    content
FROM
    global
WHERE
    name = 'definition'
LIMIT
    1
`

func (q *Queries) GetGlobalDefinition(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getGlobalDefinition)
	var content string
	err := row.Scan(&content)
	return content, err
}

const updateGlobalData = `-- name: UpdateGlobalData :exec
UPDATE
    global
SET
    content = ?
WHERE
    name = 'data'
`

func (q *Queries) UpdateGlobalData(ctx context.Context, content string) error {
	_, err := q.db.ExecContext(ctx, updateGlobalData, content)
	return err
}

const updateGlobalDefinition = `-- name: UpdateGlobalDefinition :exec
UPDATE
    global
SET
    content = ?
WHERE
    name = 'definition'
`

func (q *Queries) UpdateGlobalDefinition(ctx context.Context, content string) error {
	_, err := q.db.ExecContext(ctx, updateGlobalDefinition, content)
	return err
}
