// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: template.sql

package adminmodel

import (
	"context"
)

const countTemplate = `-- name: CountTemplate :one
SELECT
    count(*)
FROM
    template
`

func (q *Queries) CountTemplate(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTemplate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTemplateByName = `-- name: CountTemplateByName :one
SELECT
    count(*)
FROM
    template
WHERE
    name = ?
`

func (q *Queries) CountTemplateByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTemplateByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTemplate = `-- name: CreateTemplate :execlastid
INSERT INTO
    template (name, content)
VALUES
    (?, ?)
`

type CreateTemplateParams struct {
	Name    string
	Content string
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createTemplate, arg.Name, arg.Content)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM template
WHERE
    name = ?
`

func (q *Queries) DeleteTemplate(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteTemplate, name)
	return err
}

const getTemplateList = `-- name: GetTemplateList :many
SELECT
    name
FROM
    template
ORDER BY
    name DESC
LIMIT
    ?
OFFSET
    ?
`

type GetTemplateListParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GetTemplateList(ctx context.Context, arg GetTemplateListParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTemplateList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAllTemplate = `-- name: SelectAllTemplate :many
SELECT
    id, name, content
FROM
    template
`

func (q *Queries) SelectAllTemplate(ctx context.Context) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, selectAllTemplate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(&i.ID, &i.Name, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectTemplate = `-- name: SelectTemplate :many
SELECT
    id, name, content
FROM
    template
WHERE
    name = ?
LIMIT
    1
`

func (q *Queries) SelectTemplate(ctx context.Context, name string) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, selectTemplate, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(&i.ID, &i.Name, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :exec
UPDATE template
SET
    name = ?,
    content = ?
WHERE
    name = ?
`

type UpdateTemplateParams struct {
	Name    string
	Content string
	Name_2  string
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateTemplate, arg.Name, arg.Content, arg.Name_2)
	return err
}
