// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: block.sql

package publicmodel

import (
	"context"
)

const selectAllBlock = `-- name: SelectAllBlock :many
SELECT
    id, name, content, definition
FROM
    block
`

func (q *Queries) SelectAllBlock(ctx context.Context) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, selectAllBlock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.Definition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
