// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: layout.sql

package publicmodel

import (
	"context"
)

const selectLayoutByID = `-- name: SelectLayoutByID :many
SELECT
    id, name, content
FROM
    layout
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) SelectLayoutByID(ctx context.Context, id int64) ([]Layout, error) {
	rows, err := q.db.QueryContext(ctx, selectLayoutByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Layout
	for rows.Next() {
		var i Layout
		if err := rows.Scan(&i.ID, &i.Name, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
