// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package publicmodel

import (
	"time"
)

type Article struct {
	ID       int64
	Title    string
	Date     time.Time
	Author   string
	Content  string
	Slug     string
	Draft    int64
	LayoutID int64
}

type Block struct {
	ID         int64
	Name       string
	Content    string
	Definition string
}

type BlockDatum struct {
	ID        int64
	Position  int64
	Data      string
	ArticleID int64
	BlockID   int64
}

type File struct {
	ID      int64
	Name    string
	Content []byte
}

type Layout struct {
	ID      int64
	Name    string
	Content string
}

type Template struct {
	ID      int64
	Name    string
	Content string
}
