// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: article.sql

package publicmodel

import (
	"context"
	"time"
)

const getArticlesList = `-- name: GetArticlesList :many
SELECT
    title,
    date,
    author,
    slug,
    draft
FROM
    articles
WHERE
    draft = false
ORDER BY
    date DESC
LIMIT
    ?
OFFSET
    ?
`

type GetArticlesListParams struct {
	Limit  int64
	Offset int64
}

type GetArticlesListRow struct {
	Title  string
	Date   time.Time
	Author string
	Slug   string
	Draft  int64
}

func (q *Queries) GetArticlesList(ctx context.Context, arg GetArticlesListParams) ([]GetArticlesListRow, error) {
	rows, err := q.db.QueryContext(ctx, getArticlesList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArticlesListRow
	for rows.Next() {
		var i GetArticlesListRow
		if err := rows.Scan(
			&i.Title,
			&i.Date,
			&i.Author,
			&i.Slug,
			&i.Draft,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectArticleBySlug = `-- name: SelectArticleBySlug :many
SELECT
    id, title, date, author, content, slug, draft, layout_id
FROM
    articles
WHERE
    slug = ?
    and draft = false
LIMIT
    1
`

func (q *Queries) SelectArticleBySlug(ctx context.Context, slug string) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, selectArticleBySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Date,
			&i.Author,
			&i.Content,
			&i.Slug,
			&i.Draft,
			&i.LayoutID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
