// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: block_data.sql

package publicmodel

import (
	"context"
	"database/sql"
)

const selectBlockDataByArticle = `-- name: SelectBlockDataByArticle :many
SELECT
    bd.id as ` + "`" + `id` + "`" + `,
    bd.position as ` + "`" + `position` + "`" + `,
    bd.data as ` + "`" + `data` + "`" + `,
    bd.article_id as ` + "`" + `article_id` + "`" + `,
    bd.block_id as ` + "`" + `block_id` + "`" + `,
    b.name as ` + "`" + `name` + "`" + `
FROM
    block_data as bd
    LEFT JOIN block as b on b.id = bd.block_id
WHERE
    bd.article_id = ?
ORDER BY
    bd.position DESC
`

type SelectBlockDataByArticleRow struct {
	ID        int64
	Position  int64
	Data      string
	ArticleID int64
	BlockID   int64
	Name      sql.NullString
}

func (q *Queries) SelectBlockDataByArticle(ctx context.Context, articleID int64) ([]SelectBlockDataByArticleRow, error) {
	rows, err := q.db.QueryContext(ctx, selectBlockDataByArticle, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectBlockDataByArticleRow
	for rows.Next() {
		var i SelectBlockDataByArticleRow
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Data,
			&i.ArticleID,
			&i.BlockID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
