// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: block_data.sql

package publicmodel

import (
	"context"
)

const selectBlockDataByArticle = `-- name: SelectBlockDataByArticle :many
SELECT
    id, position, data, article_id, block_id
FROM
    block_data
WHERE
    article_id = ?
ORDER BY
    position DESC
`

func (q *Queries) SelectBlockDataByArticle(ctx context.Context, articleID int64) ([]BlockDatum, error) {
	rows, err := q.db.QueryContext(ctx, selectBlockDataByArticle, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlockDatum
	for rows.Next() {
		var i BlockDatum
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Data,
			&i.ArticleID,
			&i.BlockID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
