// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: file.sql

package publicmodel

import (
	"context"
)

const downloadFile = `-- name: DownloadFile :one
SELECT
    content
FROM
    files
WHERE
    uuid = ?
LIMIT
    1
`

func (q *Queries) DownloadFile(ctx context.Context, uuid string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, downloadFile, uuid)
	var content []byte
	err := row.Scan(&content)
	return content, err
}
