// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: layout.sql

package publicmodel

import (
	"context"
)

const selectBaseLayout = `-- name: SelectBaseLayout :many
SELECT
    id, name, content
FROM
    layouts
WHERE
    name like "_layout/%"
`

func (q *Queries) SelectBaseLayout(ctx context.Context) ([]Layout, error) {
	rows, err := q.db.QueryContext(ctx, selectBaseLayout)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Layout
	for rows.Next() {
		var i Layout
		if err := rows.Scan(&i.ID, &i.Name, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectLayout = `-- name: SelectLayout :many
SELECT
    id, name, content
FROM
    layouts
WHERE
    name = ?
LIMIT
    1
`

func (q *Queries) SelectLayout(ctx context.Context, name string) ([]Layout, error) {
	rows, err := q.db.QueryContext(ctx, selectLayout, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Layout
	for rows.Next() {
		var i Layout
		if err := rows.Scan(&i.ID, &i.Name, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
