// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: page.sql

package publicmodel

import (
	"context"
)

const selectPageByID = `-- name: SelectPageByID :many
SELECT
    id, name, content
FROM
    pages
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) SelectPageByID(ctx context.Context, id int64) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, selectPageByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(&i.ID, &i.Name, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
