// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: template.sql

package publicmodel

import (
	"context"
)

const selectAllTemplate = `-- name: SelectAllTemplate :many
SELECT
    id, name, content
FROM
    template
`

func (q *Queries) SelectAllTemplate(ctx context.Context) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, selectAllTemplate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(&i.ID, &i.Name, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
